# Generated by Django 3.0.6 on 2020-07-03 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer_app', '0003_auto_20200627_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stud_name', models.CharField(max_length=250)),
                ('rollNumber', models.CharField(max_length=20, unique=True)),
                ('label', models.IntegerField(max_length=999, unique=True)),
            ],
        ),
    ]
