# Generated by Django 3.0.6 on 2020-07-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer_app', '0004_attendance_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_model',
            name='label',
            field=models.IntegerField(unique=True),
        ),
    ]
