# Generated by Django 3.0.6 on 2020-07-05 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer_app', '0006_attendance_model_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance_model',
            name='created_time',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AlterField(
            model_name='attendance_model',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
