# Generated by Django 3.0.6 on 2020-07-30 16:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer_app', '0007_auto_20200705_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_model',
            name='created_time',
            field=models.TimeField(default=datetime.time(21, 36)),
        ),
    ]
