# Generated by Django 3.0.6 on 2020-07-30 16:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer_app', '0008_auto_20200730_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_model',
            name='created_time',
            field=models.TimeField(default=datetime.time(22, 11)),
        ),
        migrations.AlterField(
            model_name='attendance_model',
            name='label',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='attendance_model',
            name='rollNumber',
            field=models.CharField(max_length=20),
        ),
    ]
