# Generated by Django 3.0.6 on 2020-07-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer_app', '0010_auto_20200731_2301'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_model',
            old_name='label',
            new_name='folderLabel',
        ),
    ]
