# Generated by Django 3.0.6 on 2020-08-08 17:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognizer_app', '0012_auto_20200805_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance_model',
            name='created_time',
            field=models.TimeField(default=datetime.time(22, 59)),
        ),
    ]
